### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by quinncomendant** [mick/geojsonapp#1]
Installing on OS X 10.9 gives errors:

```
[…]
/Users/q/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[…]
```

Full output here: http://hastebin.com/uwogopipiw
Node log here: https://cloudup.com/cP5CEApi060

**Comment by mick** [comment]
@quinncomendant thanks for detailed report! I removed the dependency that is causing the error when installed with node `0.12.x`. Try geojsonapp `1.0.2`

**Comment by quinncomendant** [comment]
Version `1.0.2` appears to be unavailable:

```
[q@haywire/0 ~] npm install -g geojsonapp 1.0.2
npm ERR! fetch failed https://registry.npmjs.org/1.0.2/-/1.0.2-1.0.0.tgz
```

Does it take some time before a new npm package is available?

**Comment by mick** [comment]
`npm install -g geojsonapp`  will fetch the latest version which is `1.0.2`

or 

`npm install -g geojsonapp@1.0.2`

will fetch a specific version

**Comment by quinncomendant** [comment]
Awesome, it's working now. Lovely.

Oh, hey—just a note for the documentation. I noticed geojsonapp doesn't take a URL as input, but one can use the Process Substitution operator to load file contents from a URL using curl:

```
$ geojsonapp <(curl -s http://example.com/api/v1/resources.json)
```

😉
